permalink: /:categories/:year/:month/:day/:title
exclude: ["License.md", "Makefile", "Gemfile", "Gemfile.lock"]

author: 
  name: Toni Giorgino
  email: toni.giorgino@gmail.com
  github: tonigi

title: The PYCV module for PLUMED 2
description: Enable the implementation of collective variables (CVs) and functions in the Python language.
logo: /images/logo.png
repository: giorginolab/plumed2-pycv
url: https://giorginolab.github.io/plumed2-pycv/

show_downloads: false
markdown: kramdown
google_analytics: nil
theme: jekyll-theme-minimal
